### ISSUE TITLE
请指教

### ISSUE THREAD

**Issue by YmmLom** [Zhurp2020/AutoStudy#1]
你好，我刚刚接触selenium，然后也有了这个想法，但在处理视频静音时遇到了点困难，能否指教一下你是怎么做的
![image](https://user-images.githubusercontent.com/62608600/77441300-41339900-6e24-11ea-9bc8-8c0b8aaffda8.png)

**Comment by YmmLom** [comment]
收藏暗示（狗头）

**Comment by Zhurp2020** [comment]
我还真没试过点静音键，我是直接在系统声音设置 应用音量和设备首选项 里面直接把窗口静音的

**Comment by ymlqianzhen** [comment]
😂😂我观看了 多个用此法fuck超星的源代码，只有一个提到了静音，然后用的方法我试的不行

**Comment by YmmLom** [comment]
已解决
